enum ACTION_TYPES {
  // 设置服务端口
  SET_SERVER_PORT = "SET_SERVER_PORT",
  // 设置路径配置
  SET_PATH_CONFIG = "SET_PATH_CONFIG",

  // 设置厂商品牌列表
  SET_BRAND_LIST = "SET_BRAND_LIST",
  // 设置当前选择的厂商
  SET_CURRENT_BRAND = "SET_CURRENT_BRAND",

  // 设置资源配置
  SET_SOURCE_CONFIG = "SET_SOURCE_CONFIG",
  // 设置资源预览列表
  SET_SOURCE_DESC_LIST = "SET_SOURCE_DESC_LIST",
  // 设置资源模块配置列表
  SET_MODULE_CONF_LIST = "SET_MODULE_CONF_LIST",
  // 设置当前资源模块页面组列表
  SET_PAGE_GROUP_LIST = "SET_PAGE_GROUP_LIST",
  // 设置当前页面数据
  SET_CURRENT_PAGE_DATA = "SET_CURRENT_PAGE_DATA",

  // 设置当前选择的模块信息
  SET_CURRENT_MODULE = "SET_CURRENT_MODULE",
  // 设置当前选择的页面信息
  SET_CURRENT_PAGE = "SET_CURRENT_PAGE",

  // 初始化工程信息
  INIT_PROJECT = "INIT_PROJECT",
  // 设置工程新数据
  SET_PROJECT_DATA = "SET_PROJECT_DATA",
  // 设置工程描述数据
  SET_PROJECT_INFO = "SET_PROJECT_INFO"
}

export default ACTION_TYPES;
